const powerPartsData = [
    {
        name: "Ability Increase",
        description: "Increase the target’s Ability by +1 for the duration.",
        baseBP: 1,
        baseEnergy: 10,
        opt1Cost: 10,
        opt1Description: "Add additional +1 to the ability, to a maximum of +8. No ability can be increased above 10 using this part.",
        BPIncreaseOpt1: 0,
        opt2Cost: 4,
        opt2Description: "Increase the maximum increase cap by +1.",
        BPIncreaseOpt2: 0,
        opt3Cost: 5,
        opt3Description: "Placeholder for a third option description.",
        BPIncreaseOpt3: 0,
        altBaseEnergy: 8,
        altEnergyDescription: "Use a lower base energy cost at 8 EN, sacrificing some effectiveness.",
        altBP: 0,
        useAltCost: false,
        type: "base"
    },
    {
        name: "Increase Cost Power Part",
        description: "+50% EN: Target must overcome your power's effect(s) one additional time in order to avoid the effect(s). If the power lingers then the attempts to overcome need not be consecutive.",
        baseBP: 1,
        baseEnergy: 0.5,
        opt1Cost: 0.25,
        opt1Description: "+25% EN for each additional overcome required.",
        BPIncreaseOpt1: 0,
        opt2Cost: 0,
        opt2Description: "Placeholder for a second option description.",
        BPIncreaseOpt2: 0,
        opt3Cost: 0,
        opt3Description: "Placeholder for a third option description.",
        BPIncreaseOpt3: 0,
        altBaseEnergy: 0,
        altEnergyDescription: "",
        altBP: 0,
        useAltCost: false,
        type: "increase"
    },
    {
        name: "Decrease Cost Power Part",
        description: "-25% EN: Reduce the energy cost of the power.",
        baseBP: 1,
        baseEnergy: -0.25,
        opt1Cost: -0.125,
        opt1Description: "-12.5% EN for each additional reduction.",
        BPIncreaseOpt1: 0,
        opt2Cost: 0,
        opt2Description: "Placeholder for a second option description.",
        BPIncreaseOpt2: 0,
        opt3Cost: 0,
        opt3Description: "Placeholder for a third option description.",
        BPIncreaseOpt3: 0,
        altBaseEnergy: 0,
        altEnergyDescription: "",
        altBP: 0,
        useAltCost: false,
        type: "decrease"
    }
];

export default powerPartsData;
